version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - backend-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
